/*
copyright 2024 jack (@waffle87)
spdx-license-identifier: gpl-2.0-or-later
*/

#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif

uint16_t last_keycode;

// Left-hand home row mods
#define HOME_A LCTL_T(KC_A)
#define HOME_S LALT_T(KC_S)
#define HOME_D LGUI_T(KC_D)
#define HOME_F LSFT_T(KC_F)

// Right-hand home row mods
#define HOME_J RSFT_T(KC_J)
#define HOME_K RGUI_T(KC_K)
#define HOME_L LALT_T(KC_L) // awkward things might happen with RALT instead (this can be AltGr!)
#define HOME_QUOT RCTL_T(KC_QUOT)

// copy and paste
#define HOME_CPY LGUI(KC_C)
#define HOME_PST LGUI(KC_V)

#ifdef TAP_DANCE_ENABLE
enum {
  DOT_TD,
};

#define TD_DOT TD(DOT_TD)
#else
#define TD_DOT KC_DOT
#endif

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │ ESC  │  Q   │  W   │  E   │  R   │  T   │                │  Y   │  U   │  I   │  O   │  P   │ BSPC │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │ TAB  │HOME_A│HOME_S│HOME_D│HOME_F│  G   │                │  H   │HOME_J│HOME_K│HOME_L│HOME_Q│ ENT  │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │ COLN │  Z   │  X   │  C   │  V   │  B   │                │  N   │  M   │ COMM │TD_DOT│ SLSH │ GRV  │
 * └──────┴──────┴──────┴──────┼──────┼──────┼──────┐  ┌──────┼──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │C(KC_B│MO(1) │ LSFT │  │ SPC  │MO(2) │ DEL  │
 *                             └──────┴──────┴──────┘  └──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */
  [0] = LAYOUT_split_3x6_3(
    KC_ESC,   KC_Q,     KC_W,     KC_E,     KC_R,     KC_T,         KC_Y,     KC_U,     KC_I,     KC_O,     KC_P,       KC_BSPC,
    KC_TAB,   HOME_A,   HOME_S,   HOME_D,   HOME_F,   KC_G,         KC_H,     HOME_J,   HOME_K,   HOME_L,   HOME_QUOT,  KC_ENT,
    KC_COLN,  KC_Z,     KC_X,     KC_C,     KC_V,     KC_B,         KC_N,     KC_M,     KC_COMM,  TD_DOT,   KC_SLSH,    KC_GRV,
                                  C(KC_B),  MO(1),    KC_LSFT,      KC_SPC,   MO(2),    KC_DEL
  ),

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │      │      │      │ VOLD │ VOLU │ MUTE │                │      │HOME_C│  UP  │HOME_P│      │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │      │      │ MPRV │ MPLY │ MNXT │                │      │ LEFT │ DOWN │ RGHT │      │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │      │      │      │      │      │                │      │      │      │      │      │      │
 * └──────┴──────┴──────┴──────┼──────┼──────┼──────┐  ┌──────┼──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │      │      │      │  │      │MO(3) │      │
 *                             └──────┴──────┴──────┘  └──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */
  [1] = LAYOUT_split_3x6_3(
    XXXXXXX,  XXXXXXX,  XXXXXXX,  KC_VOLD,  KC_VOLU,  KC_MUTE,      XXXXXXX,  HOME_CPY, KC_UP,    HOME_PST, XXXXXXX,  XXXXXXX,
    XXXXXXX,  XXXXXXX,  XXXXXXX,  KC_MPRV,  KC_MPLY,  KC_MNXT,      XXXXXXX,  KC_LEFT,  KC_DOWN,  KC_RGHT,  XXXXXXX,  XXXXXXX,
    XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,      XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,
                                  _______,  _______,  _______,      _______,  MO(3),    _______
  ),

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │      │ EXLM │  AT  │ HASH │ DLR  │ PERC │                │ CIRC │ AMPR │ ASTR │ UNDS │ SCLN │ BSPC │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │ QUES │ TILD │ LCBR │ LPRN │ LBRC │                │ COLN │ DQT  │ EQL  │ PLUS │ BSLS │ ENT  │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │  LT  │  GT  │ RCBR │ RPRN │ RBRC │                │ PIPE │ MINS │ COMM │ DOT  │ SLSH │ GRV  │
 * └──────┴──────┴──────┴──────┼──────┼──────┼──────┐  ┌──────┼──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │      │MO(3) │      │  │      │      │      │
 *                             └──────┴──────┴──────┘  └──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */
  [2] = LAYOUT_split_3x6_3(
    _______,  KC_EXLM,  KC_AT,    KC_HASH,  KC_DLR,   KC_PERC,      KC_CIRC,  KC_AMPR,  KC_ASTR,  KC_UNDS,  KC_SCLN,  KC_BSPC,
    _______,  KC_QUES,  KC_TILD,  KC_LCBR,  KC_LPRN,  KC_LBRC,      KC_COLN,  KC_DQT,   KC_EQL,   KC_PLUS,  KC_BSLS,  KC_ENT,
    _______,  KC_LT,    KC_GT,    KC_RCBR,  KC_RPRN,  KC_RBRC,      KC_PIPE,  KC_MINS,  KC_COMM,  KC_DOT,   KC_SLSH,  KC_GRV,
                                  _______,  MO(3),    _______,      _______,  _______,  _______
  ),

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │QK_BOO│RM_VAL│RM_HUE│RM_SAT│RM_NEX│RM_TOG│                │ COMM │  P7  │  P8  │  P9  │ PLUS │ BSPC │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │EE_CLR│RM_VAL│RM_HUE│RM_SAT│RM_PRE│CK_TOG│                │ DOT  │  P4  │  P5  │  P6  │ MINS │ ENT  │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │      │      │      │      │ EQL  │                │  P0  │  P1  │  P2  │  P3  │ SLSH │ ASTR │
 * └──────┴──────┴──────┴──────┼──────┼──────┼──────┐  ┌──────┼──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │      │      │      │  │      │      │      │
 *                             └──────┴──────┴──────┘  └──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */
  [3] = LAYOUT_split_3x6_3(
    QK_BOOT,  RM_VALU,  RM_HUEU,  RM_SATU,  RM_NEXT,  RM_TOGG,      KC_COMM,  KC_P7,    KC_P8,    KC_P9,    KC_PLUS,  KC_BSPC,
    EE_CLR,   RM_VALD,  RM_HUED,  RM_SATD,  RM_PREV,  CK_TOGG,      KC_DOT,   KC_P4,    KC_P5,    KC_P6,    KC_MINS,  KC_ENT,
    XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  KC_EQL,       KC_P0,    KC_P1,    KC_P2,    KC_P3,    KC_SLSH,  KC_ASTR,
                                  _______,  _______,  _______,      _______,  _______,  _______
    )
};

uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record) {
  switch (keycode) {
    case LCTL_T(KC_A):
      return TAPPING_TERM + 50;
    default:
      return TAPPING_TERM;
  }
}


#ifdef TAP_DANCE_ENABLE
  // Due to keymap introspection, the old `SRC += tapdance.c` technique in rules.mk no longer works
  #include "tapdance.c"
#endif
